<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cliente by idCliente
     */
    function get_cliente($idCliente)
    {
        return $this->db->get_where('Cliente',array('idCliente'=>$idCliente))->row_array();
    }
        
    /*
     * Get all clientes
     */
    function get_all_clientes()
    {
        $this->db->order_by('idCliente', 'desc');
        return $this->db->get('Cliente')->result_array();
    }
        
    /*
     * function to add new cliente
     */
    function add_cliente($params)
    {
        $this->db->insert('Cliente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cliente
     */
    function update_cliente($idCliente,$params)
    {
        $this->db->where('idCliente',$idCliente);
        return $this->db->update('Cliente',$params);
    }
    
    /*
     * function to delete cliente
     */
    function delete_cliente($idCliente)
    {
        return $this->db->delete('Cliente',array('idCliente'=>$idCliente));
    }
}
