<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cobrancaspedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cobrancaspedido by idCobrancasPedido
     */
    function get_cobrancaspedido($idCobrancasPedido)
    {
        return $this->db->get_where('CobrancasPedido',array('idCobrancasPedido'=>$idCobrancasPedido))->row_array();
    }
        
    /*
     * Get all cobrancaspedido
     */
    function get_all_cobrancaspedido()
    {
        $this->db->order_by('idCobrancasPedido', 'desc');
        return $this->db->get('CobrancasPedido')->result_array();
    }
        
    /*
     * function to add new cobrancaspedido
     */
    function add_cobrancaspedido($params)
    {
        $this->db->insert('CobrancasPedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cobrancaspedido
     */
    function update_cobrancaspedido($idCobrancasPedido,$params)
    {
        $this->db->where('idCobrancasPedido',$idCobrancasPedido);
        return $this->db->update('CobrancasPedido',$params);
    }
    
    /*
     * function to delete cobrancaspedido
     */
    function delete_cobrancaspedido($idCobrancasPedido)
    {
        return $this->db->delete('CobrancasPedido',array('idCobrancasPedido'=>$idCobrancasPedido));
    }
}
