<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estoque_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estoque by idEstoque
     */
    function get_estoque($idEstoque)
    {
        return $this->db->get_where('Estoque',array('idEstoque'=>$idEstoque))->row_array();
    }
        
    
    /*
     * Get estoque by idEstoque
     */
    function get_estoque_by_idProduto_idFilial($idProduto, $idFilial) 
    {  
        return $this->db->get_where('Estoque', array('Produto_idProduto'=>$idProduto, 'Filial_idFilial'=>$idFilial))->row_array();
    }
    /*
     * Get all estoque
     */
    function get_all_estoque()
    {
        $this->db->order_by('idEstoque', 'desc');
        return $this->db->get('Estoque')->result_array();
    }
        
    /*
     * function to add new estoque
     */
    function add_estoque($params)
    {
        $this->db->insert('Estoque',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estoque
     */
    function update_estoque($idEstoque,$params)
    {
        $this->db->where('idEstoque',$idEstoque);
        return $this->db->update('Estoque',$params);
    }
    
    /*
     * function to delete estoque
     */
    function delete_estoque($idEstoque)
    {
        return $this->db->delete('Estoque',array('idEstoque'=>$idEstoque));
    }
}
