<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Filial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get filial by idFilial
     */
    function get_filial($idFilial)
    {
        return $this->db->get_where('Filial',array('idFilial'=>$idFilial))->row_array();
    }
        
    /*
     * Get all filiais
     */
    function get_all_filiais()
    {
        $this->db->order_by('idFilial', 'desc');
        return $this->db->get('Filial')->result_array();
    }
        
    /*
     * function to add new filial
     */
    function add_filial($params)
    {
        $this->db->insert('Filial',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update filial
     */
    function update_filial($idFilial,$params)
    {
        $this->db->where('idFilial',$idFilial);
        return $this->db->update('Filial',$params);
    }
    
    /*
     * function to delete filial
     */
    function delete_filial($idFilial)
    {
        return $this->db->delete('Filial',array('idFilial'=>$idFilial));
    }
}
