<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formapagamento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formapagamento by idFormaPagamento
     */
    function get_formapagamento($idFormaPagamento)
    {
        return $this->db->get_where('FormaPagamento',array('idFormaPagamento'=>$idFormaPagamento))->row_array();
    }
        
    /*
     * Get all formapagamento
     */
    function get_all_formapagamento()
    {
        $this->db->order_by('idFormaPagamento', 'desc');
        return $this->db->get('FormaPagamento')->result_array();
    }
        
    /*
     * function to add new formapagamento
     */
    function add_formapagamento($params)
    {
        $this->db->insert('FormaPagamento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formapagamento
     */
    function update_formapagamento($idFormaPagamento,$params)
    {
        $this->db->where('idFormaPagamento',$idFormaPagamento);
        return $this->db->update('FormaPagamento',$params);
    }
    
    /*
     * function to delete formapagamento
     */
    function delete_formapagamento($idFormaPagamento)
    {
        return $this->db->delete('FormaPagamento',array('idFormaPagamento'=>$idFormaPagamento));
    }
}
