<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itenspedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itenspedido by idItensPedido
     */
    function get_itenspedido($idItensPedido)
    {
        return $this->db->get_where('ItensPedido',array('idItensPedido'=>$idItensPedido))->row_array();
    }
        
    
    /*
     * Get itenspedido by idItensPedido
     */
    function get_itenspedido_by_idPedido_idProduto($idPedido, $idProduto)
    {
        return $this->db->get_where('ItensPedido', [ 
            'Produto_idProduto' => $idProduto,
            'PedidoEstoque_idPedidoEstoque' => $idPedido,
            'status' => 'ativo'
        ])->row_array();  
    }

    /*
     * Get all itenspedido
     */
    function get_all_itenspedido($idPedido = null)
    { 
        $this->db->select('*'); 
        $this->db->from('itenspedido');
        $this->db->join('produto', 'produto.idProduto = itenspedido.Produto_idProduto');
        
        if ($idPedido > 0) {
            $this->db->where('PedidoEstoque_idPedidoEstoque', $idPedido);
        }
        
        $this->db->order_by('idItensPedido', 'asc');
        return $this->db->get()->result_array();
    } 
        
    /*
     * function to add new itenspedido
     */
    function add_itenspedido($params)
    {
        $this->db->insert('ItensPedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itenspedido
     */
    function update_itenspedido($idItensPedido,$params)
    {
        $this->db->where('idItensPedido',$idItensPedido);
        return $this->db->update('ItensPedido',$params);
    }
    
    /*
     * function to delete itenspedido
     */
    function delete_itenspedido($idItensPedido)
    {
        return $this->db->delete('ItensPedido',array('idItensPedido'=>$idItensPedido));
    }
}
